---
version: 1
disable_existing_loggers: false
formatters:
  default:
    "()": log_schema.main.DefaultFormatter

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: default
    level: INFO
    filename: example.log

loggers:
  "":
    handlers:
      - console
      - file 
    level: INFO
    propagate: true

